export const NOTIFY_USER = "NOTIFY_USER";
export const DISABEL_BALANCE_ON_ADD = "DISABEL_BALANCE_ON_ADD";
export const DISABEL_BALANCE_ON_EDIT = "DISABEL_BALANCE_ON_EDIT";
export const ALLOW_REGISTRATION = "ALLOW_REGISTRATION";
